//Local Host

###
GET  http://localhost:8080/ HTTP/1.1

###Get all contacts
Get https://ribekacse341-team2.onrender.com

//
###
GET http://localhost:8080/contacts/6325d0e71e18e9c339520b33
//
###
GET http://localhost:8080/contacts/6325d0e71e18e9c339520b34
//
###

GET http://localhost:8080/contacts/6325d0e71e18e9c339520b35
//

// Render
###
GET https://ribekacse341-team2.onrender.com/contacts/6325d0e71e18e9c339520b33
//
###
GET https://ribekacse341-team2.onrender.com/contacts/6325d0e71e18e9c339520b34
//
###

GET https://ribekacse341-team2.onrender.com/contacts/6325d0e71e18e9c339520b35
//